CREATE TABLE homepage(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    href TEXT NOT NULL,
    src TEXT NOT NULL
);
CREATE TABLE emails(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(0) NOT NULL DEFAULT 'now()',
    to TEXT NULL,
    email TEXT NULL,
    subject TEXT NULL,
    message TEXT NULL
);
CREATE TABLE email(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    page_id INT NULL,
    src TEXT NOT NULL,
    email TEXT NOT NULL
);
CREATE TABLE page1(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    currentPage VARCHAR(30) CHECK (CURRENTPAGE IN ('')) NOT NULL,
    img_src TEXT NOT NULL,
    title TEXT NOT NULL,
    text1 TEXT NOT NULL,
    text2 TEXT NOT NULL,
    text3 TEXT NOT NULL,
    text_bottom TEXT NOT NULL
);
CREATE TABLE page3(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    currentPage VARCHAR(30) CHECK (CURRENTPAGE IN ('')) NOT NULL,
    img_src TEXT NOT NULL,
    title TEXT NOT NULL,
    text1 TEXT NOT NULL,
    text2 TEXT NOT NULL,
    text_bottom TEXT NOT NULL
);
CREATE TABLE page2(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    currentPage VARCHAR(30) CHECK (CURRENTPAGE IN ('')) NOT NULL,
    img_src TEXT NOT NULL,
    title TEXT NOT NULL,
    text1 TEXT NOT NULL,
    text2 TEXT NOT NULL,
    text3 TEXT NOT NULL,
    text_bottom TEXT NOT NULL
);
CREATE TABLE nav(
    _id INT CHECK (_id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    href TEXT NOT NULL,
    src TEXT NOT NULL
);
ALTER TABLE
    email ADD CONSTRAINT email_page_id_foreign FOREIGN KEY(page_id) REFERENCES page3(_id);